/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next'
import './global.css'

export const metadata: Metadata = {
  title: 'Lucas Codes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
